// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAwdwPNylV9gatKQ9NCDdLYxnXo8v3oQQ',
    appId: '1:687617042368:web:107cb41d9644c57fe58a25',
    messagingSenderId: '687617042368',
    projectId: 'apptodoyou',
    authDomain: 'apptodoyou.firebaseapp.com',
    storageBucket: 'apptodoyou.firebasestorage.app',
    measurementId: 'G-LJ1DJH31ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDooQ6KvOycG0doiwbr6HsWJgbL93aYiOc',
    appId: '1:687617042368:android:2cfc55693cd40953e58a25',
    messagingSenderId: '687617042368',
    projectId: 'apptodoyou',
    storageBucket: 'apptodoyou.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE00HBl6lDJP3hglLHC25WbWzcJ8SxH1Y',
    appId: '1:687617042368:ios:1edc399410596f2be58a25',
    messagingSenderId: '687617042368',
    projectId: 'apptodoyou',
    storageBucket: 'apptodoyou.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE00HBl6lDJP3hglLHC25WbWzcJ8SxH1Y',
    appId: '1:687617042368:ios:1edc399410596f2be58a25',
    messagingSenderId: '687617042368',
    projectId: 'apptodoyou',
    storageBucket: 'apptodoyou.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
